project_id = "zhpunscluuswszswsiqp"

[functions.orchestrator]
verify_jwt = false

[functions.get-schema-registry]
verify_jwt = true

[functions.query-builder]
verify_jwt = true

[functions.analytics-query]
verify_jwt = true

[functions.ai-query]
verify_jwt = true


[functions.generate-tool-definition]
verify_jwt = true

[functions.generate-tool-code]
verify_jwt = true

[functions.execute-custom-tool]
verify_jwt = true

[functions.manage-ai-settings]
verify_jwt = true