project_id = "zhpunscluuswszswsiqp"

[functions.orchestrator]
verify_jwt = false

[functions.get-schema-registry]
verify_jwt = true

[functions.query-builder]
verify_jwt = true

[functions.analytics-query]
verify_jwt = true